<template>
    <div class="page_container">
      <div class="heading">
        <h1><b><u>List Rendering</u></b></h1>
      </div>
      <p>
        List rendering in Vue.js is a fundamental feature that enables dynamic and
        efficient rendering of lists of data in the DOM. It allows you to iterate
        over an array or an iterable object and render individual items as
        elements in the user interface. Vue provides the v-for directive, which
        acts as a loop to create multiple instances of an element for each item
        in the list. This directive is especially useful when working with
        dynamic data or when you need to display collections of items such as
        posts, products, or user profiles.
      </p>
  
      <div id="part_1">
        <div class="heading"><h2><b>V-for with an object</b></h2></div>
        <p>
          In this, I will be showing the lists of the whole units I have in this trimester with the help of list rendering.
        </p>
        <ul>
          <li v-for="(value, key, index) in myunits" :key="key">
            {{ key }}: {{ value }}
          </li>
        </ul>
      </div>
      <br>
      <div id="part_2">                                                                 <!--V-for within a range-->
        <div class="heading"><h2><b>V-for with a range</b></h2></div>
        <p>In this, I will be showing the examples of the numbers from 1 to 20 generated by v-for with a range.</p>
        <span v-for="n in 20">{{ n }}</span>
      </div>
  
      <div id="part_3">
        <div class="heading"><h2><b>V-for with a template</b></h2></div>
        <p>
          In this example, I will use v-for with a template to show the grades of units with the grades that I received in trimester 1.
        </p>
        <ul>
          <li v-for="(unit, index) in units" :key="index"> <!-- "V-for with a template -->
            {{ unit.name }} ({{ unit.grade }})
          </li>
        </ul>
      </div>
  
      <br>
      <div id="part_4">
        <div class="heading"><h2><b>V-for with v-if</b></h2></div>
       
        <p>
          Here,I want to show the name of the units in which I have received the pass grade in the trimester. 
        </p>
  
        <ul>
          <li v-for="unit in newunits">                                  <!--v-for with v-if-->
            <div v-if="unit.grade=='PASS'">{{ unit.name }}</div>           
          </li>
        </ul>
      </div>
<br>
    <div id="part_5">
        <div class="heading"><h2><b>V-for with a component</b></h2></div>
    <p> In this section, I am going to show an example of v-for with a component and aims to receives the list of units with grades that , I recieved in last trimester
        by using the component that is created in the components section with the name 'Componentforlist.vue' .</p>
    <Componentforlist
        v-for="(unit, index) in newunits"
        :key="index"
        :unit="unit"
      ></Componentforlist>

    </div>
    </div>
  </template>

<script >
import Componentforlist from '../components/Componentforlist.vue'; // Import your custom component

export default {
    components: {
    Componentforlist, // Register the custom component
  },
  data() {
    return {
      myunits: {
        SIT120: 'Introduction to Responsive Web Apps',
        SIT103: 'Database Fundamentals',
        MIS201: 'Digital Business Analysis',
        SIT224: 'Information Systems and Innovation'
      },
      newunits: [
        { name: 'SIT 102', grade: 'PASS' },
        { name: 'SIT 124', grade: 'HIGH DISTINCTION' },
        { name: 'SIT 112', grade: 'CREDIT' },
        { name: 'SIT 182', grade: 'CREDIT' }
      ]
    };
  }
};
</script>

<style scoped>
  .page_container {
    background-color: lightslategrey;
    padding: 15px;
  }
  
  .heading {
    color: darkred;
  }
  
  #part_1 {
    margin-top: 20px;
    padding: 10px;
    background-color: lightcyan;
    color: darkblue;
  }
  
  #part_2 {
    background-color: orange;
    color: teal;
  }
  
  #part_3 {
    margin-top: 20px;
    padding: 15px;
    background-color: lightgreen;
    color: darkblue;
  }
  
  #part_4 {
    background-color: yellow;
    color: darkmagenta;
    padding:15px;
  }
  #part_5{
    background-color: thistle;
    padding: 15px;
  }
  </style>