<template>
  <div class="page_container">
    <div class="heading">
      <h1><b>Event Handling</b></h1>
    </div>
    <p>
      Event handling in Vue allows you to create interactive and dynamic web applications by responding to user actions with ease.
      A webpage can listen to a wide range of events and execute custom logic to update the application's state or perform various actions based on user interactions.
    </p>
    <br>
    <div class="part_1">
      <div class="heading">
        <h2>Inline Handlers</h2>
        <p>
          Inline event handlers in Vue.js allow you to directly attach event listeners and execute JavaScript code within Vue templates.
          While Vue encourages using the `v-on` directive (or its shorthand `@`) to bind event listeners to methods defined in Vue components,
          inline event handlers provide an alternative way to handle events directly in the template.
        </p>
        <br>
        <div class="example_1">
          <br>
          <p>The double value is: {{ counter }}</p> <!-- Inline Handlers are implemented here -->
          <button @click="doubleCounter">Double</button>
          <p> Here the value will get doubled as we click on the double button. This is generated by the Inline Handlers</p>
        </div>
      </div>
    </div>
    <br>
    <div class="part_2">
      <div class="heading">
        <h2>Method Handlers</h2>
      </div>
      <p>Method handlers in Vue are a way to respond to events and user interactions in a Vue.js application.
        These handlers are defined as methods in the Vue component and are used to execute custom logic when a specific event occurs.</p>
      <br>
      <div class="example_2">
        <p>The square value is: {{ squaredCounter }}</p> <!-- Method Handlers are implemented here -->
        <button @click="squareCounter">Square</button>
        <p> Here the value generated from the above section will get squared as we click on the square button. This is generated by a Method Handler.</p>

        <button @click="showAlert">Show Alert</button>
      </div>
    </div>
  </div>
</template>

<script>
import { ref } from 'vue';

export default {
  data() {
    return {
      counter: ref(2),
      squaredCounter: ref(0),
    };
  },
  methods: {
    doubleCounter() {
      this.counter *= 2; 
    },
    squareCounter() {
      this.squaredCounter = this.counter **2 ; 
    },
    showAlert() {
      alert('Inline and Method handlers are implemented !!!!');
    },
  },
};
</script>

<style scoped>
.page_container {
  background-color: darkgreen;
  color: yellow;
  padding: 15px;
}

.heading {
  color: lightcyan;
}

.part_1 {
  background-color: darkolivegreen;
}

.part_2 {
  background-color: darkturquoise;
  color: darkmagenta;
}

.example_1 {
  background-color: darkslateblue;
  margin: auto;
  text-align: center;
}

.example_2 {
  background-color: darkorange;
  margin: auto;
  text-align: center;
}
</style>
